### ISSUE TITLE
batch_size =1?

### ISSUE THREAD

**Issue by UestcJay** [idiap/GeoNeRF#12]
thanks for your geonerf! In training, after geo_reasoner, step in get_rays_pts, why only support bs=1?

**Comment by MohammadJohari** [comment]
This is mostly because of resource limitations. The geo_reasoner is memory-hungry and we only use it to reason about a single scene. For neural rendering, we sample all pixels/rays from the images that represent the very same single scene. The bs=1 in fact means a single scene, not a single image or a single ray. Unfortunately, even for a hypothetical larger GPU memory, our current implementation does not support larger bs.
